@extends('emails.layout')

@section('title', 'URGENT: Panic Alert Notification')

@section('content')
    <div class="alert alert-danger">
        <strong>🚨 URGENT NOTIFICATION</strong><br>
        A panic alert has been triggered and requires immediate attention.
    </div>

    <div style="background: #fef2f2; border: 2px solid #ef4444; border-radius: 8px; padding: 20px; margin: 24px 0;">
        <h3 style="margin: 0 0 16px 0; color: #991b1b; font-size: 18px;">Alert Details</h3>
        
        <div style="margin-bottom: 12px;">
            <strong style="color: #991b1b;">Child:</strong> {{ $childName }}
        </div>
        
        <div style="margin-bottom: 12px;">
            <strong style="color: #991b1b;">Time:</strong> {{ $alertTime }}
        </div>
        
        @if($alertMessage)
            <div style="margin-bottom: 12px;">
                <strong style="color: #991b1b;">Message:</strong><br>
                <em>"{{ $alertMessage }}"</em>
            </div>
        @endif

        @if($location)
            <div style="margin-bottom: 12px;">
                <strong style="color: #991b1b;">Location:</strong> {{ $location }}
            </div>
        @endif
    </div>

    <div class="content-text">
        <strong>Immediate Actions Required:</strong>
    </div>
    <ul>
        <li><strong>Contact the child immediately</strong> via phone or in person</li>
        <li><strong>Assess the situation</strong> and provide appropriate support</li>
        <li><strong>Consider emergency services</strong> if there's immediate danger</li>
        <li><strong>Document the incident</strong> and follow-up actions taken</li>
        <li><strong>Update the alert status</strong> once the situation is resolved</li>
    </ul>

    <div style="text-align: center; margin: 32px 0;">
        <a href="{{ $alertUrl }}" class="button" style="background-color: #ef4444;">
            View Alert Details
        </a>
    </div>

    <div class="alert alert-warning">
        <strong>Emergency Contacts:</strong><br>
        • Emergency Services: 911<br>
        • Crisis Text Line: Text HOME to 741741<br>
        • National Suicide Prevention Lifeline: 988<br>
        • SafeSpace Emergency Support: Available 24/7 through the platform
    </div>

    <div class="content-text">
        <strong>Response Protocol:</strong>
    </div>
    <ol>
        <li>Acknowledge this alert by clicking the link above</li>
        <li>Contact the child within 5 minutes</li>
        <li>Assess safety and provide immediate support</li>
        <li>Escalate to emergency services if necessary</li>
        <li>Document all actions taken in the system</li>
        <li>Follow up with appropriate care team members</li>
    </ol>

    <div class="content-text">
        This alert was automatically generated by the SafeSpace panic alert system. Please respond immediately.
    </div>

    <div class="content-text">
        <strong>SafeSpace Emergency Response Team</strong>
    </div>
@endsection